CC=gcc

integers:
	$(CC) integers-getFirstNPrimes.c -o integers-getFirstNPrimes.bin -lbiagra -lm
	$(CC) integers-isPrime.c -o integers-isPrime.bin -lbiagra -lm
	$(CC) integers-uintSumFirstNIntegers.c -o integers-uintSumFirstNIntegers.bin -lbiagra -lm
	$(CC) integers-uliFactorial.c -o integers-uliFactorial.bin -lbiagra -lm

clean:
	rm -f *.o *~ *.bin
