CC=gcc

integers:
	$(CC) integers-uintSumFirstNIntegers.c -o integers-uintSumFirstNIntegers -lbiagra -lm
	$(CC) integers-isPrime.c -o integers-isPrime -lbiagra -lm
	$(CC) integers-getFirstNPrimes.c -o integers-getFirstNPrimes -lbiagra -lm
	$(CC) integers-uliFactorial.c -o integers-uliFactorial -lbiagra -lm

clean:
	rm -f *.o *~
