dblArgumento : complejo.o dblArgumento.o
	gcc -o dblArgumento complejo.o dblArgumento.o -lm

complejo.o : complejo.c
	gcc -c complejo.c

dblArgumento.o : dblArgumento.c
	gcc -c dblArgumento.c

limpiar clean:
	rm complejo.o dblArgumento.o
