strDivComplejos : complejo.o strDivComplejos.o
	gcc -o strDivComplejos complejo.o strDivComplejos.o -lm

complejo.o : complejo.c
	gcc -c complejo.c

strDivComplejos.o : strDivComplejos.c
	gcc -c strDivComplejos.c

limpiar clean:
	rm complejo.o strDivComplejos.o
