strProdComplejos : complejo.o strProdComplejos.o
	gcc -o strProdComplejos complejo.o strProdComplejos.o

complejo.o : complejo.c
	gcc -c complejo.c

strProdComplejos.o : strProdComplejos.c
	gcc -c strProdComplejos.c

limpiar clean:
	rm complejo.o strProdComplejos.o
