strOpuComplejo : complejo.o strOpuComplejo.o
	gcc -o strOpuComplejo complejo.o strOpuComplejo.o

complejo.o : complejo.c
	gcc -c complejo.c

strOpuComplejo.o : strOpuComplejo.c
	gcc -c strOpuComplejo.c

limpiar clean:
	rm complejo.o strOpuComplejo.o
