strRestaComplejos : complejo.o strRestaComplejos.o
	gcc -o strRestaComplejos complejo.o strRestaComplejos.o

complejo.o : complejo.c
	gcc -c complejo.c

strRestaComplejos.o : strRestaComplejos.c
	gcc -c strRestaComplejos.c

limpiar clean:
	rm complejo.o strRestaComplejos.o
