CC=gcc

complex:
	$(CC) complex-addComplex.c -o complex-addComplex -lbiagra -lm
	$(CC) complex-subtractComplex.c -o complex-subtractComplex -lbiagra -lm
	$(CC) complex-multiplyComplex.c -o complex-multiplyComplex -lbiagra -lm
	$(CC) complex-divideComplex.c -o complex-divideComplex -lbiagra -lm
	$(CC) complex-dblComplexModulus.c -o complex-dblComplexModulus -lbiagra -lm
	$(CC) complex-dblComplexArg.c -o complex-dblComplexArg -lbiagra -lm
	$(CC) complex-conjugateComplex.c -o complex-conjugateComplex -lbiagra -lm
	$(CC) complex-complex2Polar.c -o complex-complex2Polar -lbiagra -lm
	$(CC) complex-polar2Complex.c -o complex-polar2Complex -lbiagra -lm

clean:
	rm -f *.o *~
