CC=gcc

complex:
	$(CC) complex-addComplex.c -o complex-addComplex.bin -lbiagra -lm
	$(CC) complex-dblComplexArg.c -o complex-dblComplexArg.bin -lbiagra -lm
	$(CC) complex-dblComplexModulus.c -o complex-dblComplexModulus.bin -lbiagra -lm
	$(CC) complex-divideComplex.c -o complex-divideComplex.bin -lbiagra -lm
	$(CC) complex-complex2Polar.c -o complex-complex2Polar.bin -lbiagra -lm
	$(CC) complex-conjugateComplex.c -o complex-conjugateComplex.bin -lbiagra -lm
	$(CC) complex-invSumComplex.c -o complex-invSumComplex.bin -lbiagra -lm
	$(CC) complex-invMulComplex.c -o complex-invMulComplex.bin -lbiagra -lm
	$(CC) complex-multiplyComplex.c -o complex-multiplyComplex.bin -lbiagra -lm
	$(CC) complex-polar2Complex.c -o complex-polar2Complex.bin -lbiagra -lm
	$(CC) complex-subtractComplex.c -o complex-subtractComplex.bin -lbiagra -lm

clean:
	rm -f *.o *~ *.bin
