strCartePolar : complejo.o strCartePolar.o
	gcc -o strCartePolar complejo.o strCartePolar.o -lm

complejo.o : complejo.c
	gcc -c complejo.c

strCartePolar.o : strCartePolar.c
	gcc -c strCartePolar.c

limpiar clean:
	rm complejo.o strCartePolar.o
