strPolarCarte : complejo.o strPolarCarte.o
	gcc -o strPolarCarte complejo.o strPolarCarte.o -lm

complejo.o : complejo.c
	gcc -c complejo.c

strPolarCarte.o : strPolarCarte.c
	gcc -c strPolarCarte.c

limpiar clean:
	rm complejo.o strPolarCarte.o
