strSumaComplejos : complejo.o strSumaComplejos.o
	gcc -o strSumaComplejos complejo.o strSumaComplejos.o

complejo.o : complejo.c
	gcc -c complejo.c

strSumaComplejos.o : strSumaComplejos.c
	gcc -c strSumaComplejos.c

limpiar clean:
	rm complejo.o strSumaComplejos.o
