strInvComplejo : complejo.o strInvComplejo.o
	gcc -o strInvComplejo complejo.o strInvComplejo.o -lm

complejo.o : complejo.c
	gcc -c complejo.c

strInvComplejo.o : strInvComplejo.c
	gcc -c strInvComplejo.c

limpiar clean:
	rm complejo.o strInvComplejo.o
