strComplejoConj : complejo.o strComplejoConj.o
	gcc -o strComplejoConj complejo.o strComplejoConj.o

complejo.o : complejo.c
	gcc -c complejo.c

strComplejoConj.o : strComplejoConj.c
	gcc -c strComplejoConj.c

limpiar clean:
	rm complejo.o strComplejoConj.o
