dblModulo : complejo.o dblModulo.o
	gcc -o dblModulo complejo.o dblModulo.o -lm

complejo.o : complejo.c
	gcc -c complejo.c

dblModulo.o : dblModulo.c
	gcc -c dblModulo.c

limpiar clean:
	rm complejo.o dblModulo.o
